name: zkSync Foundry Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Foundry zkSync Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry from Matter Labs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get latest release info
          echo "Getting latest release info..."
          DOWNLOAD_URL=$(gh api repos/matter-labs/foundry-zksync/releases/latest | jq -r '.assets[] | select(.name | contains("foundry_nightly_linux_amd64.tar.gz")) | .browser_download_url')
          
          # Create directory and download
          mkdir -p foundry-zksync
          echo "Downloading foundry..."
          gh release download --repo matter-labs/foundry-zksync --pattern '*linux_amd64.tar.gz' --dir .
          
          # Extract
          echo "Extracting..."
          tar -xzf foundry_nightly_linux_amd64.tar.gz -C foundry-zksync
          
          # Install
          echo "Installing..."
          chmod +x foundry-zksync/install
          ./foundry-zksync/install
          
          # Add to PATH
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH
          
          # Display version
          forge --version

      - name: Build
        run: |
          forge build --zksync
        
      - name: Run tests
        run: |
          forge test --zksync -vvv