name: zkSync Foundry Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Foundry zkSync Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry from Matter Labs
        run: |
          # Download directly from Matter Labs CI artifacts
          mkdir -p foundry-zksync
          cd foundry-zksync
          
          # Download and install foundryup
          curl -L https://raw.githubusercontent.com/matter-labs/foundry-zksync/main/foundryup/install > install
          chmod +x install
          ./install
          
          # Add foundry to PATH for this session
          export PATH="$HOME/.foundry/bin:$PATH"
          
          # Install specific version
          foundryup --version nightly --repo matter-labs/foundry-zksync
          
          # Add to PATH for subsequent steps
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH
          
          # Display version
          forge --version

      - name: Build
        run: |
          forge build --zksync
        
      - name: Run tests
        run: |
          forge test --zksync -vvv